version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/documents:/app/documents
      - ./backend/leads.db:/app/leads.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - ANONYMIZED_TELEMETRY=False
      - GROQ_API_KEY=gsk_YOUR_GROQ_KEY # Keep your existing Groq key here
      - WHATSAPP_TOKEN=EAAOMphUTBfwBR4PQD2OJLNgntkVJ6mJg8J3B5ER1ZA0a7JrCJtFWALqZAAPzNNeDU24ws8ieu5jPHbtTE73PuySspEOJFrJ34ZBNlyOqgbNTge7z60rYXSx7GadvfUCZAdbiUEDK74ezeNMQETVpQXYxQAqwvBfuoOZBVsyVWL9rxZCj2NYdHDFswWLnXaCgZDZD
      - WHATSAPP_PHONE_ID=1238435072684922

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend