version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/documents:/app/documents
      - ./backend/leads.db:/app/leads.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - ANONYMIZED_TELEMETRY=False
      - GROQ_API_KEY=gsk_YOUR_GROQ_KEY # Keep your existing Groq key here
      - WHATSAPP_TOKEN=EAAOMphUTBfwBRzhAd4mwYaB0nfAgBfpySjAV6zs7ZARxi0D9p46DQXHF4niG5ZCFvfYc5sa50j8gvWKWZAjLJhaLFGLGlLtET8fOEIXAZAv7HhBjTtkZCxlVyQtBRu6r3er5qOuutOaknPWtVl7STvW15kzINUI76Oax2WCZBvJQ1XZANMnjhjCgdg5orDTZCdNLBWJbSWW1mO7QLrJsdGTkHCxMO1hSZCZC3C5CDQGAPpm4Sht2WFd7NLVIq3CaU6hvmT95U02Lk5wd8ZCXjZC9C0wgU3A9jacr26TeigZDZD
      - WHATSAPP_PHONE_ID=1238435072684922

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend